### ISSUE TITLE
Missing sokoban platform

### ISSUE THREAD

**Issue by Solliet** [Unity-Technologies/obstacle-tower-source#11]
Hi,
I encountered a bug while running recording a demonstration. These are the initialization parameters:

```toml
name='demo1'
[reset_parameters]
tower-seed=100
starting-floor=0
dense-reward=0
lighting-type=1
visual-theme=0
agent-perspective=1
allowed-rooms=2
allowed-modules=2
allowed-floors=2
total-floors=100
default-theme=0
```

In floor 21, there is a bug and the sokoban platform isn't showing.

<img width="2032" alt="Screenshot 2020-01-12 at 6 36 22 PM" src="https://user-images.githubusercontent.com/52372765/72222239-35497200-356b-11ea-9a57-ac8c908a8a6b.png">
<img width="2032" alt="Screenshot 2020-01-12 at 6 36 30 PM" src="https://user-images.githubusercontent.com/52372765/72222240-35e20880-356b-11ea-97fc-193a10d0a1c8.png">
<img width="2032" alt="Screenshot 2020-01-12 at 6 36 46 PM" src="https://user-images.githubusercontent.com/52372765/72222241-35e20880-356b-11ea-8c1d-21debcf55826.png">
<img width="2032" alt="Screenshot 2020-01-12 at 6 37 00 PM" src="https://user-images.githubusercontent.com/52372765/72222242-35e20880-356b-11ea-8426-c0cfee8e4d70.png">

If I start over from the same floor, the platform is there.

<img width="2032" alt="Screenshot 2020-01-12 at 6 49 15 PM" src="https://user-images.githubusercontent.com/52372765/72222340-4d6dc100-356c-11ea-89c1-aed092b84ac8.png">

The bug seems to depend on the previous floor because I began from 20 this time and went to 21 and it didn't show up.

<img width="2032" alt="Screenshot 2020-01-12 at 6 51 30 PM" src="https://user-images.githubusercontent.com/52372765/72222370-a89fb380-356c-11ea-85d1-a2b8393bb5c9.png">
